### ISSUE TITLE
Error: Failed to activate the atom-ide-javascript package

### ISSUE THREAD

**Issue by claytonrcarter** [atom-ide-community/atom-ide-javascript#45]
### Description

After upgrading to Atom 1.61-beta (which includes an upgrade from Electron 9->11), this package has stopped working.

### Steps to Reproduce

1. Open Atom Beta w/ a JS file.

**Reproduces how often:**

Every time, so far.

### Versions

**Atom**: 1.61.0-beta0 x64
**Electron**: 11.4.12
**OS**: macOS 12.1
**Thrown From**: [atom-ide-javascript](https://github.com/atom-ide-community/atom-ide-javascript) package 1.5.0

```
❯ atom-beta --version
Atom    : 1.61.0-beta0
Electron: 11.4.12
Chrome  : 87.0.4280.141
Node    : 12.18.3

❯ apm-beta --version
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.61.0-beta0
python 2.7.18
git 2.32.0

```

### Additional Information

Although this package is failing to activate, it appears that the underlying issue might actually be elsewhere? The stacktrace does seem to actually include any code w/i this package. Rather, it's going through several of the dependencies from w/i the `atom-ide-base` project, ending in `atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js`, (transpiled) line 45, which is really [line 26](https://github.com/atom-community/atom-ide-base/blob/master/nuclide/nuclide-commons-ui/Dropdown.js#L26), ie:

```
// this is just the parts that I think are relevant
import invariant from 'assert';
import remote from '@atom-ide-community/nuclide-commons/electron-remote';

invariant(remote != null);
```

Where `invariant(remote != null);` is what's actually triggering the issue.

I've never worked with any of these packages before, but if someone can give me some hints, I could take a whack at a fix. Any ideas? Thank you!

### Stack Trace

Failed to activate the atom-ide-javascript package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-handlebars 1.3.0 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-ide-vue 1.4.6 
atom-linter-phpstan 2.2.0 
atom-phpunit 1.3.0 
atom-tailwindcss 0.9.0 
atom-typescript 14.4.0 
atom-vscode 0.1.0 
zap-to-char 0.1.1 
atomic-vale 1.9.0 
autocomplete-paths 2.17.0 
blade-snippets 0.2.0 
block-travel 1.0.7 
busy-signal 2.0.1 
calc 0.4.0 
center-line 1.4.0 
change-case 0.6.5 
clipboard-plus 0.5.1 
docblockr 0.14.2 
elastic-tabstops 1.3.1 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.47 
firefox-syntax 4.2.0 
git-blame 1.8.0 
git-tab-status 1.9.2 
go-plus 6.1.0 
highlight-selected 0.17.0 
ide-css 0.4.0 
ide-go 0.12.3 
ide-php 0.7.18 
ide-rust 1.1.1 
ide-typescript 0.9.5 
intentions 2.1.1 
javascript-drag-import 0.1.13 
js-hyperclick 1.13.3 
jumpy 5.0.2 
keyboard-scroll 0.7.0 
language-awk 0.1.12 
language-blade 0.46.0 
language-docker 1.1.8 
language-dotenv 1.2.0 
language-htaccess 0.2.0 
language-ledger 0.4.5 
language-lua 0.9.11 
language-markdown 0.37.0 
language-vue 0.26.0 
line-diff-details-plus 1.9.1 
linter 3.4.0 
linter-eslint 9.0.0 
linter-php 1.6.1 
linter-phpcs 1.8.1 
linter-phpmd 2.0.2 
linter-shellcheck 1.6.0 
linter-tlint 0.0.1 
linter-ui-default 3.4.1 
linter-yaml 1.1.3 
magic-reflow 0.3.0 
minimap 4.40.0 
minimap-find-and-replace 5.0.9 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.6 
minimap-selection 4.5.5 
multi-paste 0.3.1 
neon 0.2.0 
pain-split 1.4.0 
php-cs-fixer 4.3.0 
php-ide-serenata 5.4.0 
php-twig 4.0.0 
prettier-atom 0.60.1 
project-manager 3.3.8 
remember-file-positions 0.2.3 
remember-folds 0.3.0 
semanticolor 3.7.0 
Sublime-Style-Column-Selection 1.7.5 
terminal-commands 1.5.0 
x-terminal 13.0.25 
```

**Comment by ghost** [comment]
This is related to https://github.com/atom-community/ide-python/issues/483

I'm also experiencing this issue, with a similar stack trace giving ```call.getFileName is not a function``` as the primary complaint. 



<sup>This comment is simply to improve record keeping, and to link similar issues.</sup>

**Comment by rjousse18** [comment]
Same here, 1.63

**Comment by aminya** [comment]
As a quick dirty fix, commenting out this line should fix the issue, but the debugger doesn't work.
https://github.com/atom-community/atom-ide-javascript/blob/9c566a97b9f6be5f588077fcd776313c10dd59b1/src/main.js#L4

The electron remote backend changed inside Atom. I suggested a fix if someone wants to continue the work.
https://github.com/atom-community/atom-ide-base/pull/92
