### ISSUE TITLE
call.getFileName is not a function

### ISSUE THREAD

**Issue by rjousse18** [atom-ide-community/atom-ide-javascript#50]
### Description

I have this error when I launch Atom

### Steps to Reproduce

1. Open JS project on Atom

### Versions

**Atom**: 1.63.0 x64
**Electron**: 11.5.0
**OS**: Windows 11
**Thrown From**: [atom-ide-javascript](https://github.com/atom-ide-community/atom-ide-javascript) package 1.5.0

### Stack Trace

Failed to activate the atom-ide-javascript package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:278:25)
    at innerOk (assert.js:372:17)
    at ok (assert.js:392:3)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.63.0/resources/app/static/<embedded>:11:149229)
```

### Commands

```
     -0:26.6.0 Code-Time:refresh-flow-nodes (atom-workspace.workspace.scrollbars-visible-always.theme-visual-studio-dark-syntax.theme-atom-visual-studio-code-ui)
  2x -0:17.1.0 Music-Time:update-recommend-treeview (atom-workspace.workspace.scrollbars-visible-always.theme-visual-studio-dark-syntax.theme-atom-visual-studio-code-ui)
     -0:15.4.0 Music-Time:refresh-treeview (atom-workspace.workspace.scrollbars-visible-always.theme-visual-studio-dark-syntax.theme-atom-visual-studio-code-ui)
     -0:13.3.0 Music-Time:update-recommend-treeview (atom-workspace.workspace.scrollbars-visible-always.theme-visual-studio-dark-syntax.theme-atom-visual-studio-code-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline undefined 
atom-ide-signature-help 0.16.0 
atom-ide-ui 0.13.0 
atom-linter-node-dependencies 1.5.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 14.4.0 
atom-visual-studio-code-ui 2.1.0 
autoclose-html-plus 0.27.2 
autocomplete 0.47.0 
autocomplete-java 1.2.7 
autocomplete-jsp 1.2.1 
autocomplete-paths 2.17.0 
autocomplete-sql 0.5.0 
autosave-onchange 1.5.1 
busy 0.7.0 
busy-signal 2.0.1 
code-time 4.4.24 
color-picker 2.3.0 
convert-file-encoding 0.1.0 
css-color-name 0.4.0 
declarations 1.1.3 
docblockr 0.14.2 
dockerletion 0.2.0 
file-icons 2.1.47 
file-watcher 2.0.0 
git-merge 0.4.1 
git-plus 8.7.1 
gitlab-manager 0.2.2 
highlight-selected 0.17.0 
html-tag-auto-complete 2.1.0 
hyperclick 0.1.5 
ide-css 0.4.0 
ide-docker 0.1.0 
ide-html 0.7.0 
ide-java 0.9.1 
ide-json 0.2.1 
ide-python 1.9.7 
ide-typescript 0.9.5 
image-preview 0.4.0 
increment-selection 0.3.0 
intentions 2.1.1 
intentions-colorpicker 1.0.1 
intentions-numbers 1.0.4 
ionic-preview 0.7.0 
java-generator 2.2.3 
java-importer 1.4.1 
javascript-drag-import 0.1.13 
js-hyperclick 1.19.0 
language-apache 1.8.0 
language-babel 2.85.0 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-html-angular 1.0.16 
language-kotlin 0.5.0 
language-mongodb 0.3.1 
language-pgsql 0.2.3 
language-powershell 5.0.0 
linter 3.4.0 
linter-docker 0.3.2 
linter-eslint 9.0.1 
linter-eslint-node 1.0.6 
linter-package-json-validator 2.0.0 
linter-sass-lint 1.9.0 
linter-ui-default 3.4.1 
mongo 0.3.0 
music-time 2.1.16 
npm-install 4.0.4 
pdf-view 0.73.0 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
pretty-json 2.1.2 
process-palette 0.19.3 
project-manager 3.3.8 
quick-query 1.2.0 
quick-query-mssql 0.1.5 
quick-query-sqlite 0.4.1 
react 0.18.0 
rest-client 1.3.5 
script 3.32.2 
seti-dark-monokai 0.1.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
split-diff 1.6.1 
spotify-remote 1.0.2 
spring-boot 1.8.0 
symbols-tree-nav 0.15.8 
symbols-tree-view 0.14.0 
sync-settings 5.2.16 
TabNine 4.0.7 
teletype 0.13.4 
todo-show 2.3.2 
tomorrow-night-eighties-ng2-syntax 1.1.0 
tool-bar 1.4.4 
tool-bar-expert 0.6.1 
tree-view-copy-relative-path 1.2.0 
visual-studio-dark-syntax 0.2.0 
```

**Comment by rjousse18** [comment]
Deplicate of #45 sorry !
